// Auto-generated by the generator
// Don't manually edit this file

// @flow

import type {Action} from '../../types'
import type {DashboardState} from '../types'

import {setDashboardReducer} from './setDashboard'
import {initialState} from './initialState'

export const dashboardReducer = (state: DashboardState = initialState, action: Action<any>): DashboardState => {
  switch (action.type) {
    case 'dashboard/SET_DASHBOARD':
      return setDashboardReducer(state, action)
    default:
      return state
  }
}
