// Auto-generated by the generator
// Don't manually edit this file

// @flow

import type {Action} from '../../types'
import type {DashboardState} from '../types'

import {initialState} from './initialState'

export const dashboardReducer = (state: DashboardState = initialState, action: Action<any>): DashboardState => {
  switch (action.type) {
    default:
      return state
  }
}
