// Auto-generated by the generator
// Don't manually edit this file

// @flow

import {enterDashboardEffect} from './enterDashboard'
import {createStateEffect} from './createState'

export const dashboardEffects = [
  enterDashboardEffect,
  createStateEffect,
]
