// Auto-generated by the generator
// Don't manually edit this file

// @flow

import {setDashboard} from './setDashboard'
import {createState} from './createState'

export const dashboardActions = {
  setDashboard,
  createState,
}
