// Auto-generated by the generator
// Don't manually edit this file

// @flow

import {openProject} from './openProject'
import {createProject} from './createProject'
import {checkIsProject} from './checkIsProject'

export const homeActions = {
  openProject,
  createProject,
  checkIsProject,
}
