// Auto-generated by the generator
// Don't manually edit this file

// @flow

import {openProject} from './openProject'
import {createProject} from './createProject'

export const homeActions = {
  openProject,
  createProject,
}
