// Auto-generated by the generator
// Don't manually edit this file

// @flow

import type {HomeState} from './home/types'
import type {DashboardState} from './dashboard/types'

export type Action<P> = {
  type: string,
  payload: P
}

export type Reducer<S, P> = (state: S, action: Action<P>) => S

export type Effect = Generator<any, any, any>

export type ApplicationState = {
  home: HomeState,
  dashboard: DashboardState,
}
