// Auto-generated by the generator
// Don't manually edit this file

// @flow

import {openProjectEffect} from './openProject'
import {createProjectEffect} from './createProject'

export const homeEffects = [
  openProjectEffect,
  createProjectEffect,
]
