// Auto-generated by the generator
// Don't manually edit this file

// @flow

import type {Action} from '../../types'
import type {HomeState} from '../types'

import {initialState} from './initialState'

export const homeReducer = (state: HomeState = initialState, action: Action<any>): HomeState => {
  switch (action.type) {
    default:
      return state
  }
}
